name: commentme
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  cloud_firestore: ^5.4.2
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_database: ^11.1.3
  firebase_remote_config: ^5.1.2
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
