// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJZEPBamYq4R2JLLWQUHMwsbtiQ4McfYM',
    appId: '1:1080666676198:web:4bb83b8589e4cc6a959427',
    messagingSenderId: '1080666676198',
    projectId: 'commentme-4af72',
    authDomain: 'commentme-4af72.firebaseapp.com',
    storageBucket: 'commentme-4af72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB42iWwrYhyoIK2DO_7wrmYHcRMiXrCyf0',
    appId: '1:1080666676198:android:ef80407ca598296f959427',
    messagingSenderId: '1080666676198',
    projectId: 'commentme-4af72',
    storageBucket: 'commentme-4af72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf5hYBERte-z_FPpCK4hjc_3B4lJrlqv8',
    appId: '1:1080666676198:ios:d5cf89ba931ef5ad959427',
    messagingSenderId: '1080666676198',
    projectId: 'commentme-4af72',
    storageBucket: 'commentme-4af72.appspot.com',
    iosBundleId: 'com.example.commentme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf5hYBERte-z_FPpCK4hjc_3B4lJrlqv8',
    appId: '1:1080666676198:ios:d5cf89ba931ef5ad959427',
    messagingSenderId: '1080666676198',
    projectId: 'commentme-4af72',
    storageBucket: 'commentme-4af72.appspot.com',
    iosBundleId: 'com.example.commentme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJZEPBamYq4R2JLLWQUHMwsbtiQ4McfYM',
    appId: '1:1080666676198:web:aa850a28b700cb9f959427',
    messagingSenderId: '1080666676198',
    projectId: 'commentme-4af72',
    authDomain: 'commentme-4af72.firebaseapp.com',
    storageBucket: 'commentme-4af72.appspot.com',
  );

}